server:
  port: 8080

spring:
  mvc.favicon.enabled:  false
  servlet:
    multipart:
    max-file-size: 100MB
    max-request-size: 100MB

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hospital
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 1
      min-idle: 1
      max-active: 10
      # 配置获取连接等待超时的时间
      max-wait: 30000
      validation-query: SELECT 1 FROM DUAL
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000

  ## Redis 配置
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    ## Redis服务器地址
    host: 127.0.0.1
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        #spring.redis.pool.max-active=8
        max-active: 8
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        #spring.redis.pool.max-wait=-1
        max-wait: -1
        ## 连接池中的最大空闲连接
        #spring.redis.pool.max-idle=8
        max-idle: 8
        ## 连接池中的最小空闲连接
        #spring.redis.pool.min-idle=0
        min-idle: 0
    ## 连接超时时间（毫秒）
    timeout: 3000

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    # 开启驼峰自动映射
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl